//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Axsis.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public long Id_Usuario { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(50, ErrorMessage = "El Nombre de Usuario debe contener entre 7 y 50 caracteres", MinimumLength = 7)]
        public string Nombre_Usuario { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(50, ErrorMessage = "La Contraseña debe contener entre 10 y 50 caracteres", MinimumLength = 10)]
        [DataType(DataType.Password)]
        public string Contraseña { get; set; }

        [DataType(DataType.Password)]
        [StringLength(50, ErrorMessage = "La contraseña debe contener entre 10 y 50 caracteres", MinimumLength = 10)]
        [DisplayName("Confirmar Contraseña")]
        //[Compare("Contraseña")]
        public string ContraseñaConfirmada { get; set; }

        public bool Estatus { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public String Sexo { get; set; }
    }
}
